# Generated by Django 5.0.4 on 2024-04-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
